# Docker profile — overrides application.properties
spring.datasource.url=SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bjj_coach?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=bjjuser
spring.datasource.password=bjjpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring_jpa_properties_hibernate_dialect= org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

jwt.secret=bjjcoach-super-secret-key-change-this-in-production-2024
jwt.expiration=86400000

groq.api.key=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

server.port=8080